// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjwwoasnyzusgzqniyuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qd3dvYXNueXp1c2d6cW5peXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTM1MTgsImV4cCI6MjA3MTc4OTUxOH0.fbYNUiyT7nx1cPDsoVLS5mn0F6dLJ662hfsgHbs0MOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});